export const en = {
    dir: 'LTR',
    home: 'Home',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    emailVerified: 'Email Verified',
    hello: 'Hi, %{name}!',
    DogParks: 'Dog Parks',
    chat: 'Chat',
    Password: 'Password',
    account: 'חשבון',
    createAcבountFormTitle: 'הרשמה - מילוי פרטים',
    Submitting: 'Submitting..',
    Submit: 'Submit',
    continueAsGuest: 'Continue as Guest',
    WelcomeToDogfeel: 'Welcome to Dogfeel!',
    'Sign Up': 'Sign Up',
    'Forget Password?': 'Forget password?',
    Settings: 'Settings',
    'Save Changes': 'שמור שינויים',
    'Change Password': 'שנה סיסמה',
    'Change Email': 'שנה אימייל',
    'Delete Account': 'מחק חשבון',
    InputYourEmail: 'Input your email',
    '': '',
    '': '',
};
