export const he = {
    dir: 'RTL',
    home: 'בית',
    login: 'התחברות',
    Login: 'התחברות',
    logout: 'התנתק',
    Password: 'סיסמה',
    password: 'סיסמה',
    email: 'אימייל',
    emailVerified: 'אימות אימייל',
    account: 'חשבון',
    createAcבountFormTitle: 'הרשמה - מילוי פרטים',
    hello: 'היי, %{name}!',
    DogParks: 'גינות כלבים',
    chat: "צ'אט",
    Submitting: 'שולח',
    Submit: 'שלח',
    continueAsGuest: 'המשך כאורח',
    WelcomeToDogfeel: 'ברוכים הבאים לדוגפי!',
    InputYourEmail: 'הכנס את האימייל שלך',
    Continuing: 'טוען',
    enterPassword: 'הכנס סיסמה',
    confirmPassword: 'אימות סיסמה',
    enterConfirmPassword: 'הכנס סיסמה בשנית',
    enterFirstName: 'שם פרטי',
    firstName: 'שם פרטי',
    enterLastName: 'הכנס שם משפחה',
    lastName: 'שם משפחה',
    'Sign Up': 'הירשם',
    returnToPrevScreen: 'חזור למסך קודם',
    createAccountFormTitle: 'צור משתמש',
    emailIsRequired: 'נא הכנס כתובת אימייל',
    'Invalid email': 'אימייל לא תקין',
    'Password is required': 'סיסמה נדרשת',
    'Email Is Required': 'נא הכנס כתובת אימייל',
    'New email is required': 'נדרש מייל חדש',
    'Minimum 8 characters': 'לפחות 8 תווים',
    'Passwords must match': 'הסיסמאות אינן תואמות',
    'Forget Password?': 'שכחת סיסמה?',

    Settings: 'הגדרות',
    'Save Changes': 'שמור שינויים',
    'Change Password': 'שנה סיסמה',
    'Change Email': 'שנה אימייל',
    'Delete Account': 'מחק חשבון',
    introTitle1: 'מעקב וניהול צרכיו של כלביך',
    introSubTitle1:
        'לעולם לא תשכחו לטפל בכלבכם, אוכל, טיולים, חיסונים, תרופות. כל בני הבית עוזרים בטיפול בכלב',
    introTitle2: 'גינות כלבים',
    introSubTitle2:
        'מצא תמיד את הגינה הקרובה לביתך, דבר עם מבקרי הגינה בצאט, גלה  מי נמצא בה בזמן אמת והזמן חברים להצטרף',
    introTitle3: 'משפחה וחברים',
    introSubTitle3: 'העזר בבני המשפחה לניהול חיי הכלב, שמור על קשר והזמן חברים להצטרף לטיול',
    introTitle4: 'דיווח ואיתור כלב אבוד',
    introSubTitle4:
        'מצאת כלב אבוד? צלם אותו. תמונה, מיקום וזמן יתווספו למאגר המידע. אבד לך הכלב? חפש אותו במאגר וגלה היכן הוא נראה לאחרונה',
};
